### ISSUE TITLE
benchmark required

### ISSUE THREAD

**Issue by ZiXuanVickyLu** [zfergus/eigen-cuda-example#1]
Dear author：
~Hi. I am so happy to see this repo which have tried sth I'm really concerned. I have managed to achieve the same goal, which is to use raw eigen in CUDA kernel or just in device. 
But there is another concern: whether this linear algebra routine may influence the efficiency because CUDA‘s philosophy wants developer to use a lean and computing dense kernel but Eigen may provide a BLACK_BOX liked class template. As a result, it may not as efficient as 'Vector' and 'Matrix' type developed by user (with raw data array) or packaging the 'glm'.
Relevant benchmark are required :-)

**Comment by zfergus** [comment]
Hi, thank you for your interest in this example. I was curious if this is true that Eigen is so much slower on CUDA so I added a baseline comparison where I implement the `norm()` function directly in CUDA for a simple struct of three floats. 

Here are the results:
```
-------------------------------------------------------------------------------
Benchmark Eigen CUDA
-------------------------------------------------------------------------------
benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
CPU                                            100             1    112.801 ms
                                        1.12905 ms    1.12778 ms    1.13112 ms
                                        8.03569 us    5.55349 us    14.2046 us

GPU                                            100             1     215.41 ms
                                        2.06718 ms    2.06463 ms     2.0722 ms
                                        17.6048 us      10.65 us     31.431 us

GPU_NO_EIGEN                                   100             1    206.347 ms
                                        2.08118 ms    2.07448 ms    2.09016 ms
                                        39.3221 us    31.3717 us    48.9792 us
```

It seems like in this simple case Eigen CUDA vs raw CUDA does not make a difference. I am still confused by why the serial CPU implementation is 2x faster, but that is another issue.

**Comment by ZiXuanVickyLu** [comment]
Thanks for your effect! :-)
